[profile.default]
src = 'contracts'
out = 'artifacts_forge'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    '@chainlink/=node_modules/@chainlink/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@eth-optimism/=node_modules/@eth-optimism/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'erc721a-upgradeable/=node_modules/erc721a-upgradeable/',
    'erc721a/=node_modules/erc721a/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-std/=lib/forge-std/src/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
    'operator-filter-registry/=node_modules/operator-filter-registry/',
    'solmate/=lib/solmate/src/',
]
solc_version = '0.8.14'
optimizer = true
optimizer_runs = 100
# See more config options https://github.com/foundry-rs/foundry/tree/master/config